// Admin SDK is restricted to the demo emulator; auth/mail transports are test doubles.
process.env.VAULT_GITHUB_REPOSITORY='mingwonkim/obsidian-vault';process.env.VAULT_GITHUB_PATH='';process.env.GCLOUD_PROJECT='demo-mkhub';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.VAULT_OTP_PEPPER='test-only-pepper';process.env.VAULT_FIREBASE_API_KEY='test-only-public-key';
const {test,beforeEach}=require('node:test'),assert=require('node:assert/strict');
let sent=[],used=new Set();
const {vaultHandler,api}=require('../functions/index')._private;
const {getFirestore}=require('firebase-admin/firestore'),{getAuth}=require('firebase-admin/auth');const db=getFirestore(),auth=getAuth();
const owner={uid:'owner-fixture',email:'kmin5940@naver.com',email_verified:true,vault_owner:true,vault_recovery:true,vault_access:false,vault_otp_at:Date.now()};
auth.verifyIdToken=async token=>JSON.parse(token);auth.getUserByEmail=async()=>({uid:'owner-fixture',emailVerified:true});auth.createCustomToken=async(uid,claims)=>JSON.stringify({...owner,...claims,uid});
function call(action,data={},claims){return vaultHandler({body:{action,...data},ip:'127.0.0.1',get:()=>claims?'Bearer '+JSON.stringify(claims):''});}
beforeEach(async()=>{sent=[];used=new Set();global.fetch=async(url,options)=>{const body=JSON.parse(options.body);sent.push(body);if(url.includes(':sendOobCode'))return{ok:true,json:async()=>({email:body.email})};const invalid=body.oobCode==='expired'||used.has(body.oobCode);used.add(body.oobCode);return{ok:!invalid,json:async()=>invalid?{error:{message:'INVALID_OOB_CODE'}}:{idToken:JSON.stringify({...owner,email:body.oobCode==='other'?'other@example.com':owner.email})}}};await db.recursiveDelete(db.collection('mk_security'))});
test('Three-stage verification, lockout and email recovery rotate session version',async()=>{const passwords=['first','123456','나무'];const initial=JSON.parse((await call('set-pin',{passwords},owner)).token);assert.equal(initial.vault_access,true);const stored=(await db.doc('mk_security/access').get()).data();assert.equal(stored.passwords.length,3);assert(!JSON.stringify(stored).includes('first'));const verified=JSON.parse((await call('verify-pin',{passwords},owner)).token);assert.equal(verified.vault_version,initial.vault_version);for(let i=0;i<5;i++)await assert.rejects(call('verify-pin',{passwords:['wrong','123456','나무']},owner));await assert.rejects(call('verify-pin',{passwords},owner),e=>e.status===429);const reset=JSON.parse((await call('set-pin',{passwords:['reset']},owner)).token);assert.equal(reset.vault_version,initial.vault_version+1);await assert.rejects(call('set-pin',{passwords:['stale']},initial),e=>e.status===401);await assert.rejects(call('set-pin',{passwords:['wrong-owner']},{...owner,email:'attacker@example.com'}),e=>e.status===401);});
test('HTTP rejects oversized JSON even without Content-Length',async()=>{let status;const res={set(){},status(n){status=n;return this},json(){}};await api(()=>{throw Error('must not execute')})({method:'POST',is:()=>true,get:()=>'',body:{padding:'x'.repeat(33000)}},res);assert.equal(status,400);});
test('GitHub sync ignores client repository/token and never exports drawing bearer URLs',async t=>{const {githubHandler}=require('../functions/index')._private;process.env.VAULT_GITHUB_TOKEN='server-fixture-token';await db.doc('mk_security/access').set({version:1});await db.doc('mk_app/data/memos/github-fixture').set({t:'Private note',b:'Text fixture',type:'note',c:1,u:2,canvas_path:'mk_drawings/a',canvas_url:'https://fixture.invalid/?token=do-not-export'});const original=global.fetch,calls=[];t.after(()=>{global.fetch=original});global.fetch=async(url,options)=>{calls.push({url,options});const repo=url==='https://api.github.com/repos/mingwonkim/obsidian-vault';return{ok:true,status:repo?200:options.method==='GET'?404:200,json:async()=>repo?{private:true}:{}}};await githubHandler({body:{action:'push-note',id:'github-fixture',repository:'attacker/public',token:'attacker-token'},get:()=> 'Bearer '+JSON.stringify({...owner,vault_access:true,vault_version:1})});assert(calls.every(c=>c.url.startsWith('https://api.github.com/repos/mingwonkim/obsidian-vault')));const put=calls.find(c=>c.options.method==='PUT');assert.equal(put.options.headers.Authorization,'Bearer server-fixture-token');const text=Buffer.from(JSON.parse(put.options.body).content,'base64').toString();assert.match(text,/Text fixture/);assert(!text.includes('do-not-export'));});
test('GitHub refuses public repositories and reports failed writes',async t=>{const {githubHandler}=require('../functions/index')._private;await db.doc('mk_security/access').set({version:1});const original=global.fetch;t.after(()=>{global.fetch=original});const req={body:{action:'push-note',id:'github-fixture'},get:()=> 'Bearer '+JSON.stringify({...owner,vault_access:true,vault_version:1})};global.fetch=async()=>({ok:true,status:200,json:async()=>({private:false})});await assert.rejects(githubHandler(req),e=>e.status===503);await db.doc('mk_app/data/memos/github-fixture').set({t:'fixture'});global.fetch=async url=>({ok:!url.includes('/contents/'),status:url.includes('/contents/')?404:200,json:async()=>({private:true})});await assert.rejects(githubHandler(req),e=>e.status===502);});
test('Firebase sends a link to the fixed owner; client cannot override address or return URL',async()=>{await call('request-link',{email:'attacker@example.com',continueUrl:'https://attacker.invalid',mode:'recover'});assert.deepEqual(sent[0],{requestType:'EMAIL_SIGNIN',email:'kmin5940@naver.com',continueUrl:'https://xn--zf0bu7y.com/?vault=recover',canHandleCodeInApp:true});await assert.rejects(call('request-link'),e=>e.status===429);});
test('Only a valid unused owner email link creates email proof, never vault access',async()=>{await assert.rejects(call('complete-link',{code:'expired'}),e=>e.status===400);await assert.rejects(call('complete-link',{code:'other'}),e=>e.status===403);const first=JSON.parse((await call('complete-link',{code:'valid'})).token);assert.equal(first.vault_access,false);assert.equal(first.vault_recovery,true);await assert.rejects(call('complete-link',{code:'valid'}),e=>e.status===400);await assert.rejects(call('complete-link',{code:''}),e=>e.status===400);});
