// Isolated browser fixtures; real Firebase and email are never called.
const{test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const{chromium}=require('playwright');let browser;
before(async()=>{browser=await chromium.launch()});after(()=>browser.close());
async function fixture(t,{configured=true,link=true,mode='open'}={}){
 const ctx=await browser.newContext();t.after(()=>ctx.close());await ctx.route('https://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><body><button id="open">Open</button><textarea></textarea><canvas id="memoDrawCanvas"></canvas></body>'}));const p=await ctx.newPage();await p.goto('https://fixture.test/'+(link?'?mode=signIn&oobCode=fixture-link&vault='+mode:''));await p.evaluate(()=>{localStorage.setItem('mk_gh_pat','old-fixture');sessionStorage.setItem('mk_unlocked','1')});await p.addScriptTag({content:fs.readFileSync('vault-client.js','utf8')});await p.addStyleTag({content:fs.readFileSync('vault-client.css','utf8')});
 await p.evaluate(async({configured})=>{
  window.calls=[];window.downloads=0;window.rejectLink=false;window.rejectPin=false;window.delay=0;
  const owner={email:'kmin5940@naver.com',email_verified:true,vault_owner:true,vault_otp_at:Date.now()},a={currentUser:null};window.fakeAuth=a;
  const m={browserSessionPersistence:{},setPersistence:async()=>{},signInWithCustomToken:async(a,token)=>{a.currentUser={getIdToken:async()=>token,getIdTokenResult:async()=>({claims:{...owner,vault_access:token==='access',vault_recovery:token==='mail'}})}},signOut:async()=>{a.currentUser=null}};
  window.fetch=async(url,options)=>{const b=JSON.parse(options.body);calls.push(b);if(delay)await new Promise(r=>setTimeout(r,delay));let result;if(b.action==='request-link')result={sent:true};if(b.action==='complete-link')result=rejectLink?{error:'링크가 만료됐거나 이미 사용됐습니다.'}:{token:'mail'};if(b.action==='pin-state')result={configured};if(b.action==='verify-pin')result=rejectPin?{error:'암호가 일치하지 않습니다.'}:{token:'access'};if(b.action==='set-pin')result={token:'access'};return{ok:!result.error,json:async()=>result}};
  await MKVault.init(a,m,{}, {ref:(_s,path)=>({path}),getBlob:async()=>{downloads++;return new Blob(['private fixture'],{type:'text/plain'})}});
 },{configured});return p;
}
async function email(p){await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('.vault-pattern'))}
async function draw(p,dots){await p.waitForFunction(()=>document.querySelector('.vault-pattern'));const pts=await p.locator('[data-dot]').evaluateAll((els,dots)=>dots.map(i=>{const r=els[i].getBoundingClientRect();return[r.x+r.width/2,r.y+r.height/2]}),dots);await p.mouse.move(...pts[0]);await p.mouse.down();for(const pt of pts.slice(1))await p.mouse.move(...pt,{steps:6});await p.mouse.up();}
const pins=p=>p.evaluate(()=>calls.filter(c=>c.action==='verify-pin').map(c=>c.passwords));
test('Fixed link recipient, no OTP/email field, retired token, forged flag rejected',async t=>{const p=await fixture(t,{link:false});assert.equal(await p.evaluate(()=>MKVault.hasAccess()),false);assert.equal(await p.evaluate(()=>localStorage.getItem('mk_gh_pat')),null);await p.evaluate(()=>MKVault.recover());await p.waitForFunction(()=>document.querySelector('h2').textContent==='메일을 확인해주세요');assert.match(await p.locator('.vault-access-description').textContent(),/kmin5940@naver.com/);assert.equal(await p.locator('input').count(),0);assert.deepEqual(await p.evaluate(()=>calls[0]),{action:'request-link',mode:'recover'});});
test('Opening asks for the pattern directly, no email; short pattern never submits; middle dots auto-join',async t=>{const p=await fixture(t,{link:false});await p.evaluate(()=>MKVault.unlock());await draw(p,[0,1,2]);assert.match(await p.locator('[role=alert]').textContent(),/4개/);assert.deepEqual(await pins(p),[]);assert.equal(await p.evaluate(()=>calls.some(c=>c.action==='request-link')),false);assert.equal(await p.evaluate(async()=>{try{await MKVault.resolveURL('mk-private:mk_files/a');return false}catch(e){return true}}),true);await draw(p,[0,2,8,6]);await p.waitForFunction(()=>MKVault.hasAccess());assert.deepEqual(await pins(p),[['0125876']]);assert.equal(await p.evaluate(()=>document.querySelector('.vault-access')),null);assert.match(await p.evaluate(()=>MKVault.resolveURL('mk-private:mk_files/a')),/^blob:/);});
test('Forgot link from pattern screen; unconfigured vault asks for email setup',async t=>{const p=await fixture(t,{link:false,configured:false});await p.evaluate(()=>MKVault.unlock());await p.waitForFunction(()=>document.querySelector('h2').textContent==='비밀번호 찾기');await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>calls.some(c=>c.action==='request-link'&&c.mode==='recover'));const q=await fixture(t,{link:false});await q.evaluate(()=>MKVault.unlock());await q.waitForFunction(()=>document.querySelector('.vault-pattern'));await q.locator('.vault-access-secondary').click();assert.equal(await q.locator('h2').textContent(),'비밀번호 찾기');});
test('Recovery link sets a new pattern with confirmation; mismatch restarts',async t=>{const p=await fixture(t,{mode:'recover'});await email(p);await draw(p,[0,1,2,5]);await p.waitForFunction(()=>document.querySelector('h2').textContent==='한 번 더 확인');await draw(p,[0,3,6,7]);await p.waitForFunction(()=>document.querySelector('h2').textContent==='새 패턴 설정');assert.match(await p.locator('[role=alert]').textContent(),/일치하지/);await draw(p,[0,1,2,5]);await p.waitForFunction(()=>document.querySelector('h2').textContent==='한 번 더 확인');await draw(p,[0,1,2,5]);await p.waitForFunction(()=>MKVault.hasAccess());assert.deepEqual(await p.evaluate(()=>calls.filter(c=>c.action==='set-pin').map(c=>c.passwords)),[['0125']]);});
test('Expired link rejects login and offers a new link without email entry',async t=>{const p=await fixture(t);await p.evaluate(()=>rejectLink=true);await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('[role=alert]').textContent);assert.equal(await p.evaluate(()=>fakeAuth.currentUser),null);await p.locator('.vault-access-secondary').click();await p.waitForFunction(()=>calls.some(c=>c.action==='request-link'));assert.equal(await p.locator('input').count(),0);});
test('Closing during link exchange prevents late login',async t=>{const p=await fixture(t);await p.evaluate(()=>delay=200);await p.locator('.vault-access-submit').click();await p.locator('[data-close]').click();await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>fakeAuth.currentUser),null);});
test('Wrong pattern shows error and grants no access',async t=>{const p=await fixture(t,{link:false});await p.evaluate(()=>{rejectPin=true;MKVault.unlock()});await draw(p,[4,5,8,7]);await p.waitForFunction(()=>document.querySelector('[role=alert]').textContent.includes('일치하지'));assert.equal(await p.evaluate(()=>MKVault.hasAccess()),false);assert.equal(await p.locator('.vault-pattern').count(),1);});
test('Arrow cursor presses, moves into dialog and yields to writing/drawing',async t=>{const p=await fixture(t,{link:false});await p.addStyleTag({content:fs.readFileSync('hub-cursor.css','utf8')});await p.addScriptTag({content:fs.readFileSync('hub-cursor.js','utf8')});await p.locator('#open').hover();await p.mouse.down();assert.match(await p.locator('#mkCursor').getAttribute('class'),/mk-cur-down/);await p.mouse.up();await p.locator('textarea').hover();assert.equal(await p.locator('#mkCursor').evaluate(e=>e.style.opacity),'0');await p.locator('canvas').hover();assert.equal(await p.locator('html').evaluate(e=>e.classList.contains('mk-cursor-draw')),true);await p.evaluate(()=>MKVault.recover());await p.locator('[data-close]').hover();assert.equal(await p.locator('dialog #mkCursor').count(),1);await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!document.documentElement.classList.contains('mk-cursor-on'));});
test('Actual main CSP permits fixed-recipient link requests and has no secret settings',async t=>{const ctx=await browser.newContext();t.after(()=>ctx.close());await ctx.route(/firestore\.googleapis\.com|identitytoolkit\.googleapis\.com|securetoken\.googleapis\.com|firebasestorage\.googleapis\.com/,r=>r.abort());let requests=0;await ctx.route('https://asia-northeast3-mingwon-hub.cloudfunctions.net/vault',r=>{requests++;assert.deepEqual(r.request().postDataJSON(),{action:'request-link',mode:'recover'});return r.fulfill({contentType:'application/json',body:JSON.stringify({sent:true})})});const p=await ctx.newPage();await p.goto(process.env.MK_PREVIEW_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.MKVault);await p.evaluate(()=>{mkFinishArrival();setPage('settings');sendPasswordRecoveryEmail()});await p.waitForFunction(()=>document.querySelector('.vault-access h2')?.textContent==='메일을 확인해주세요');assert.equal(requests,1);assert.equal(await p.locator('#ghPatInput,#ghRepoInput,#ghPathInput,#recoveryEmailInput').count(),0);});
