// Isolated browser fixtures: no Firebase connection and no real email is sent.
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright');let browser;
before(async()=>{browser=await chromium.launch()});after(()=>browser.close());
async function fixture(t,{configured=true,stages=3}={}){
 const ctx=await browser.newContext();t.after(()=>ctx.close());await ctx.route('https://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><body><button id="open">Open</button><textarea></textarea><canvas id="memoDrawCanvas"></canvas></body>'}));
 const p=await ctx.newPage();await p.goto('https://fixture.test/');await p.evaluate(()=>{localStorage.setItem('mk_gh_pat','fixture-old-token');sessionStorage.setItem('mk_unlocked','1')});
 await p.addScriptTag({content:fs.readFileSync('vault-client.js','utf8')});await p.addStyleTag({content:fs.readFileSync('vault-client.css','utf8')});
 await p.evaluate(async({configured,stages})=>{
  window.calls=[];window.opens=0;window.downloads=0;window.rejectCode=false;window.rejectPin=false;window.delay=0;
  const owner={email:'kmin5940@naver.com',email_verified:true,vault_owner:true,vault_otp_at:Date.now()},a={currentUser:null};window.fakeAuth=a;
  const m={browserSessionPersistence:{},setPersistence:async()=>{},signInWithCustomToken:async(a,token)=>{a.currentUser={getIdToken:async()=>token,getIdTokenResult:async()=>({claims:{...owner,vault_access:token==='access'}})}},signOut:async()=>{a.currentUser=null}};
  window.fetch=async(url,options)=>{const b=JSON.parse(options.body);calls.push(b);if(delay)await new Promise(r=>setTimeout(r,delay));let result;
   if(b.action==='request-code')result={challengeId:'a'.repeat(48)};
   if(b.action==='verify-code')result=rejectCode?{error:'인증번호가 틀렸거나 만료됐습니다.'}:{token:'mail'};
   if(b.action==='pin-state')result={configured,stages};
   if(b.action==='verify-pin')result=rejectPin?{error:'암호가 일치하지 않습니다.'}:{token:'access'};
   if(b.action==='set-pin')result={token:'access'};
   return{ok:!result.error,json:async()=>result};
  };
  await MKVault.init(a,m,{}, {ref:(_s,path)=>({path}),getBlob:async()=>{downloads++;return new Blob(['private fixture'],{type:'text/plain'})}});
 },{configured,stages});return p;
}
async function email(p,recovery=false){await p.evaluate(recovery=>recovery?MKVault.recover():MKVault.requireAccess(()=>opens++),recovery);if(!recovery)await p.locator('.vault-access-submit').click();await p.locator('[name=code]').fill('123456');await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('[data-secret]'));}
test('Fixed recipient, retired browser token and forged local unlock flag',async t=>{const p=await fixture(t);assert.equal(await p.evaluate(()=>MKVault.hasAccess()),false);assert.equal(await p.evaluate(()=>localStorage.getItem('mk_gh_pat')),null);await p.evaluate(()=>MKVault.recover());await p.locator('[name=code]').waitFor();assert.match(await p.locator('.vault-access-description').textContent(),/kmin5940@naver.com/);assert.equal(await p.locator('input[type=email]').count(),0);assert.deepEqual(await p.evaluate(()=>calls[0]),{action:'request-code'});});
test('Email proof alone cannot read private files; three stages unlock once',async t=>{const p=await fixture(t);await email(p);assert.equal(await p.evaluate(()=>MKVault.hasAccess()),false);assert.equal(await p.evaluate(async()=>{try{await MKVault.resolveURL('mk-private:mk_files/a');return false}catch(e){return true}}),true);const inputs=p.locator('[data-secret]');for(const [i,v]of ['first','123456','나무가 있는 집'].entries())await inputs.nth(i).fill(v);await p.locator('[data-eye]').nth(2).click();assert.equal(await inputs.nth(2).inputValue(),'나무가 있는 집');await p.evaluate(()=>{delay=100;document.querySelector('form').requestSubmit();document.querySelector('form').requestSubmit()});await p.waitForFunction(()=>opens===1);assert.equal(await p.evaluate(()=>calls.filter(c=>c.action==='verify-pin').length),1);assert.deepEqual(await p.evaluate(()=>calls.find(c=>c.action==='verify-pin').passwords),['first','123456','나무가 있는 집']);assert.match(await p.evaluate(()=>MKVault.resolveURL('mk-private:mk_files/a')),/^blob:/);assert.equal(await p.evaluate(()=>downloads),1);});
test('Recovery allows one-stage enrollment with confirmation',async t=>{const p=await fixture(t);await email(p,true);await p.locator('[data-secret]').first().fill('new-password');await p.locator('.vault-access-submit').click();assert.equal(await p.locator('[data-secret]').count(),1);await p.locator('[data-secret]').fill('new-password');await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>MKVault.hasAccess());assert.deepEqual(await p.evaluate(()=>calls.find(c=>c.action==='set-pin').passwords),['new-password']);});
test('Wrong code/PIN retain form, and IME Enter does not submit',async t=>{const p=await fixture(t);await p.evaluate(()=>{rejectCode=true;MKVault.recover()});await p.locator('[name=code]').fill('000000');await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('[role=alert]').textContent);assert.equal(await p.evaluate(()=>fakeAuth.currentUser),null);await p.evaluate(()=>rejectCode=false);await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('[data-secret]'));await p.evaluate(()=>{const i=document.querySelector('[data-secret]');i.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true}));document.querySelector('form').requestSubmit()});assert.equal(await p.evaluate(()=>calls.filter(c=>c.action==='set-pin').length),0);});
test('Closing during code verification prevents late login',async t=>{const p=await fixture(t);await p.evaluate(()=>MKVault.recover());await p.locator('[name=code]').fill('123456');await p.evaluate(()=>delay=200);await p.locator('.vault-access-submit').click();await p.locator('[data-close]').click();await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>fakeAuth.currentUser),null);});
test('Arrow cursor presses, moves into dialog and yields to writing/drawing',async t=>{const p=await fixture(t);await p.addStyleTag({content:fs.readFileSync('hub-cursor.css','utf8')});await p.addScriptTag({content:fs.readFileSync('hub-cursor.js','utf8')});await p.locator('#open').hover();await p.mouse.down();assert.match(await p.locator('#mkCursor').getAttribute('class'),/mk-cur-down/);await p.mouse.up();assert.doesNotMatch(await p.locator('#mkCursor').getAttribute('class'),/mk-cur-down/);await p.locator('textarea').hover();assert.equal(await p.locator('#mkCursor').evaluate(e=>e.style.opacity),'0');await p.locator('canvas').hover();assert.equal(await p.locator('html').evaluate(e=>e.classList.contains('mk-cursor-draw')),true);await p.evaluate(()=>MKVault.recover());await p.locator('[data-close]').hover();assert.equal(await p.locator('dialog #mkCursor').count(),1);await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>!document.documentElement.classList.contains('mk-cursor-on'));assert.equal(await p.locator('html').evaluate(e=>e.classList.contains('mk-cursor-on')),false);});
test('Wrong server PIN preserves the stage values and blocks access',async t=>{const p=await fixture(t);await email(p);for(const[i,v]of ['wrong','123456','나무'].entries())await p.locator('[data-secret]').nth(i).fill(v);await p.evaluate(()=>rejectPin=true);await p.locator('.vault-access-submit').click();await p.waitForFunction(()=>document.querySelector('[role=alert]').textContent);assert.equal(await p.evaluate(()=>MKVault.hasAccess()),false);assert.equal(await p.locator('[data-secret]').nth(2).inputValue(),'나무');assert.equal(await p.evaluate(()=>opens),0);});
test('Actual main page CSP permits fixed-recipient recovery and hides backend settings',async t=>{const ctx=await browser.newContext();t.after(()=>ctx.close());await ctx.route(/firestore\.googleapis\.com|identitytoolkit\.googleapis\.com|securetoken\.googleapis\.com|firebasestorage\.googleapis\.com/,r=>r.abort());let requests=0;await ctx.route('https://asia-northeast3-mingwon-hub.cloudfunctions.net/vault',r=>{requests++;assert.deepEqual(r.request().postDataJSON(),{action:'request-code'});return r.fulfill({contentType:'application/json',body:JSON.stringify({challengeId:'a'.repeat(48)})})});const p=await ctx.newPage();await p.goto(process.env.MK_PREVIEW_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.MKVault);await p.evaluate(()=>{mkFinishArrival();setPage('settings');sendPasswordRecoveryEmail()});await p.locator('[name=code]').waitFor();assert.equal(requests,1);assert.equal(await p.locator('#ghPatInput,#ghRepoInput,#ghPathInput,#recoveryEmailInput').count(),0);assert.match(await p.locator('.vault-access-description').textContent(),/kmin5940@naver.com/);});
